### ISSUE TITLE
Unexpected CC state 0x2 - unable to reset.

### ISSUE THREAD

**Issue by martbhell** [NVIDIA/gpu-admin-tools#7]
Hello! This is with current latest gpu_tool and v2023.11.15.
All reset and cc commands I've tried return this.
6 out of 8 H100s I could turn on /off CC. But in two I can not. nvidia-smi sees the GPUs and some simple use of the GPU works.
Any ideas how to get CC back to off?

```bash
2024-12-09,08:36:19.096 INFO     Selected GPU 0000:a3:00.0 H100-SXM 0x2330 BAR0 0x98042000000
Traceback (most recent call last):
  File "/home/user/gpu-admin-tools/nvidia_gpu_tools.py", line 5689, in <module>
    main()
  File "/home/user/gpu-admin-tools/nvidia_gpu_tools.py", line 5283, in main
    cc_mode = gpu.query_cc_mode()
              ^^^^^^^^^^^^^^^^^^^
  File "/home/user/nvidia_gpu_tools.py", line 4242, in query_cc_mode
    return self.query_cc_mode_hopper()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/nvidia_gpu_tools.py", line 4235, in query_cc_mode_hopper
    raise GpuError(f"Unexpected CC state 0x{cc_reg}")
gpu.error.GpuError: Unexpected CC state 0x2
```

**Comment by pjaroszynski** [comment]
@martbhell you did the correct workaround. This state is not supposed to be possible, but e.g. an interrupted tool invocation could lead to it. I just pushed a new version https://github.com/NVIDIA/gpu-admin-tools/releases/tag/v2024.12.06 that relaxes this error and returns `"invalid-devtools-only-fix-by-setting-cc-mode"` as the CC mode for this case.
